/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/form1': RouteRecordInfo<'/form1', '/form1', Record<never, never>, Record<never, never>>,
    '/form2': RouteRecordInfo<'/form2', '/form2', Record<never, never>, Record<never, never>>,
    '/form3': RouteRecordInfo<'/form3', '/form3', Record<never, never>, Record<never, never>>,
  }
}
